package main

// Golden values in this file were generated by running CPython's repr() over
// each input, not hand-written — the point is to pin what Python actually does,
// including the cases the fixture corpus never reaches (floats, ints, dicts,
// and the exact escape Python picks per character class).

import (
	"math"
	"testing"
)

func TestPyReprString(t *testing.T) {
	cases := []struct{ in, want string }{
		{"simple", "'simple'"},
		{"it's", "\"it's\""},
		{"say \"hi\"", "'say \"hi\"'"},
		{"it's \"odd\"", "'it\\'s \"odd\"'"},
		{"tab\there", "'tab\\there'"},
		{"nl\nhere", "'nl\\nhere'"},
		{"cr\rhere", "'cr\\rhere'"},
		{"\x01", "'\\x01'"},
		{"\x7f", "'\\x7f'"},
		{"back\\slash", "'back\\\\slash'"},
		{"ünïcodé", "'ünïcodé'"},
		{"—✓", "'—✓'"},
		{"\u00a0", "'\\xa0'"},
		{"\u2028", "'\\u2028'"},
		{"😀", "'😀'"},
		{"", "''"},
		{"'both\"", "'\\'both\"'"},
	}
	for _, tc := range cases {
		if got := PyReprString(tc.in); got != tc.want {
			t.Errorf("PyReprString(%q) = %s, want %s", tc.in, got, tc.want)
		}
	}
}

func TestPyReprFloat(t *testing.T) {
	cases := []struct {
		in   float64
		want string
	}{
		{0.0, "0.0"},
		{math.Copysign(0, -1), "-0.0"},
		{1.0, "1.0"},
		{1.5, "1.5"},
		{0.1, "0.1"},
		{2.5, "2.5"},
		{-2.75, "-2.75"},
		{1000000000000000.0, "1000000000000000.0"},
		{1e+16, "1e+16"},
		{1e+17, "1e+17"},
		{0.0001, "0.0001"},
		{1e-05, "1e-05"},
		{1e+100, "1e+100"},
		{1.5e+300, "1.5e+300"},
		{0.3333333333333333, "0.3333333333333333"},
		{123456789012345.6, "123456789012345.6"},
		{5e-324, "5e-324"},
		{1.7976931348623157e+308, "1.7976931348623157e+308"},
	}
	for _, tc := range cases {
		if got := PyReprFloat(tc.in); got != tc.want {
			t.Errorf("PyReprFloat(%v) = %s, want %s", tc.in, got, tc.want)
		}
	}
}

// TestPyReprValue covers the container and scalar forms the enum message can
// interpolate. The list form is the one the shipped schema exercises today:
// `%s` of a Python list emits a list *literal* with repr'd elements, which is
// neither Go's %v nor its %q.
func TestPyReprValue(t *testing.T) {
	mustDecode := func(t *testing.T, raw string) Value {
		t.Helper()
		v, err := DecodeOrdered([]byte(raw))
		if err != nil {
			t.Fatalf("DecodeOrdered(%s): %v", raw, err)
		}
		return v
	}
	cases := []struct{ raw, want string }{
		{`["unit", "integration"]`, `['unit', 'integration']`},
		{`[1, 2.0, true, null]`, `[1, 2.0, True, None]`},
		{`[]`, `[]`},
		{`["a"]`, `['a']`},
		{`[["x"], {"k": "v"}]`, `[['x'], {'k': 'v'}]`},
		{`{"b": 1, "a": 2}`, `{'b': 1, 'a': 2}`},
		{`true`, `True`},
		{`false`, `False`},
		{`null`, `None`},
		{`-0`, `0`},
		{`12345678901234567890123`, `12345678901234567890123`},
		{`1e2`, `100.0`},
		{`"x"`, `'x'`},
	}
	for _, tc := range cases {
		if got := PyRepr(mustDecode(t, tc.raw)); got != tc.want {
			t.Errorf("PyRepr(%s) = %s, want %s", tc.raw, got, tc.want)
		}
	}
}

// PyStr differs from PyRepr for a bare string only; containers still repr their
// elements. This is what makes the enum message's two interpolations differ.
func TestPyStr(t *testing.T) {
	if got := PyStr("plain"); got != "plain" {
		t.Errorf(`PyStr("plain") = %s, want plain`, got)
	}
	list, err := DecodeOrdered([]byte(`["unit", "integration", "request", "system"]`))
	if err != nil {
		t.Fatal(err)
	}
	want := `['unit', 'integration', 'request', 'system']`
	if got := PyStr(list); got != want {
		t.Errorf("PyStr(list) = %s, want %s", got, want)
	}
}
