// Command sha256sums emits and verifies a SHA256SUMS manifest for a set of
// release artifacts. It is a build-host tool, like tests/cross/inspect-artifact
// beside it: scripts/build-release.sh builds it for the host up front and runs
// it, and it is never itself shipped.
//
// # What a manifest is for, and what it is NOT
//
// schema_test.go states this repository's ruling on invisible build-time
// snapshots: "an embedded asset is invisible ... nothing about reading the
// resulting binary says which bytes went in", and the remedy it ratified is a
// pinned digest. A released binary is the same shape and strictly more exposed
// — it leaves the build host and travels over the network. The release script's
// checks all run on the build host and leave nothing behind; the manifest
// is what carries their subject across.
//
// It is an IDENTITY and INTEGRITY record, not a signature. It says "these are
// the bytes this run produced", so a truncated download, a mangled mirror, or
// an artifact swapped for a different build is detectable by anyone who kept
// the manifest. It says nothing about WHO produced them: it is generated by the
// same run that built the artifacts, so an attacker who can replace an artifact
// can replace the manifest beside it. Signing and provenance are a different
// mechanism and are deliberately not claimed here — claiming otherwise would be
// the vacuous green this project keeps having to name.
//
// # Why a Go program rather than `sha256sum`
//
// `sha256sum` is GNU coreutils and is ABSENT on a stock macOS host, which
// build-release.sh accepts as a build host — its TARGETS include darwin/amd64
// and darwin/arm64, and it refuses to run on a host no target matches, so macOS
// is one of only two host families that can complete a release. Reaching for
// bare `sha256sum` would reproduce, exactly, the `ldd` defect that file's header
// documents: a tool that cannot speak the platform prints a refusal, the
// surrounding shell scores the absence of evidence as evidence of absence, and
// half the release matrix passes a check that never ran.
//
// Detecting sha256sum/shasum/openssl in order and dying when none is present is
// the other honest option. This one was chosen because Go's crypto/sha256 is
// portable BY CONSTRUCTION — there is no host to probe and therefore no probe to
// get wrong — and because the toolchain is already a hard prerequisite of the
// script (it is cross-compiling Go). schema_test.go already digests with exactly
// this stdlib path, so this is the same mechanism one level up rather than a
// second, weaker one.
//
// The emitted FORMAT is nonetheless the standard coreutils/shasum text format —
//
//	<64 lowercase hex>␠␠<basename>
//
// — so that a consumer who never heard of this tool verifies a download with
// their own platform's `sha256sum -c SHA256SUMS` or `shasum -a 256 -c
// SHA256SUMS`. The portability problem is the BUILD host's; it must not be
// exported to the adopter.
//
// # Why check mode also asserts the manifest describes the whole directory
//
// `sha256sum -c` answers "is every listed file intact", which leaves the
// converse open: an artifact sitting in the release that no manifest row
// describes. That is the same shape as the retired-artifact defect
// build-release.sh's header documents — a file present under a green summary
// line that counted only what the run built. So check mode additionally
// requires that the manifest's directory hold nothing beyond the manifest and
// its own entries. A downstream consumer's `sha256sum -c` will not do this;
// the release run does it before promoting, which is where it belongs.
//
// # Usage
//
//	sha256sums -o path/to/SHA256SUMS file...   # emit; entries are basenames
//	sha256sums -c path/to/SHA256SUMS           # verify, beside the manifest
//
// Exit 0 when the manifest was written, or when every entry matched and nothing
// was unlisted. Exit 1 when the set was examined and found WRONG (a digest
// mismatch, a listed file missing, an unlisted file present) — every problem is
// printed, not just the first. Exit 2 when the set could not be examined at all:
// an unreadable or malformed manifest, an I/O failure, a bad invocation. Those
// two are kept apart for the reason inspect-artifact keeps its own apart —
// "could not check" must never be readable as either a pass or a substantive
// failure.
package main

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/yatfa-ai/open-test-intent/tests/cross/internal/report"
)

// digestHexLen is the width of a SHA-256 digest in the manifest's hex encoding.
const digestHexLen = sha256.Size * 2

// fieldSeparator is the two spaces coreutils writes between the digest and the
// name in TEXT mode. Binary mode writes " *" instead; both GNU sha256sum and
// BSD/perl shasum read either, and text mode is what every platform's tool
// prints by default, so it is what is emitted here.
const fieldSeparator = "  "

func main() {
	emitTo := flag.String("o", "", "emit a manifest to this path, describing the files named as operands")
	checkAt := flag.String("c", "", "verify this manifest against the files in its own directory")
	flag.Parse()

	switch {
	case *emitTo != "" && *checkAt != "":
		usage("-o and -c are the two modes; give exactly one")

	case *emitTo != "":
		if flag.NArg() == 0 {
			usage("-o needs at least one file to digest")
		}
		if err := emit(*emitTo, flag.Args()); err != nil {
			fmt.Fprintf(os.Stderr, "sha256sums: %v\n", err)
			os.Exit(2)
		}
		os.Exit(0)

	case *checkAt != "":
		if flag.NArg() != 0 {
			usage("-c takes no operands; the manifest names the files itself")
		}
		// The 0/1/2 translation lives in report because inspect-artifact makes
		// the same one, and the scripts that read these codes discriminate all
		// three.
		problems, notes, err := verify(*checkAt)
		report.Exit("sha256sums", problems, notes, err)

	default:
		usage("give either -o <manifest> <file>... or -c <manifest>")
	}
}

func usage(why string) {
	fmt.Fprintf(os.Stderr, "sha256sums: %s\n", why)
	fmt.Fprintln(os.Stderr, "usage: sha256sums -o <manifest> <file>...")
	fmt.Fprintln(os.Stderr, "       sha256sums -c <manifest>")
	os.Exit(2)
}

// emit writes a manifest describing files, one row per operand, sorted by name.
//
// Rows carry BASENAMES. The manifest is written beside the artifacts it
// describes and is consumed from that directory, so an absolute path would both
// leak the build host's staging directory into a published file and be wrong
// everywhere it was read. Sorting makes the manifest a deterministic function of
// the set — the same artifacts in a different argument order produce the same
// bytes, which matters for a script whose loop already pays for reproducible
// builds.
func emit(manifestPath string, files []string) error {
	manifestName := filepath.Base(manifestPath)

	type row struct{ name, sum string }
	rows := make([]row, 0, len(files))
	seen := make(map[string]bool, len(files))

	for _, f := range files {
		name := filepath.Base(f)
		if err := checkName(name); err != nil {
			return fmt.Errorf("%s: %w", f, err)
		}
		if name == manifestName {
			return fmt.Errorf("%s: refusing to list the manifest %q as one of its own entries", f, manifestName)
		}
		if seen[name] {
			// Two operands from different directories sharing a basename would
			// produce a manifest that cannot tell them apart — and, verified in
			// its own directory, would silently check one file twice.
			return fmt.Errorf("%s: two operands share the basename %q, which a manifest of basenames cannot distinguish", f, name)
		}
		seen[name] = true

		sum, err := digest(f)
		if err != nil {
			return err
		}
		rows = append(rows, row{name: name, sum: sum})
	}

	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })

	var b strings.Builder
	for _, r := range rows {
		b.WriteString(r.sum)
		b.WriteString(fieldSeparator)
		b.WriteString(r.name)
		b.WriteString("\n")
	}
	if err := os.WriteFile(manifestPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("could not write %s: %w", manifestPath, err)
	}
	return nil
}

// verify re-reads every file the manifest names, FROM DISK, and compares it
// against the recorded digest. Re-reading is the whole point: a manifest that is
// generated and never read again is a step that reports success having verified
// nothing, and would pass just as happily over an artifact corrupted the instant
// after it was digested.
//
// A non-nil error means the manifest itself could not be used. Problems are
// findings about the artifacts, and all of them are returned rather than only
// the first, so one run reports the whole story.
func verify(manifestPath string) (problems, notes []string, err error) {
	dir := filepath.Dir(manifestPath)
	manifestName := filepath.Base(manifestPath)

	listed, order, err := parseManifest(manifestPath)
	if err != nil {
		return nil, nil, err
	}

	for _, name := range order {
		path := filepath.Join(dir, name)
		got, derr := digest(path)
		if derr != nil {
			if errors.Is(derr, fs.ErrNotExist) {
				// Listed and absent is a finding about the SET, not an inability
				// to check: the manifest asserts this file is part of the
				// release and it is not there.
				problems = append(problems, fmt.Sprintf("%s is listed in %s but is not there", name, manifestName))
				continue
			}
			return nil, nil, derr
		}
		if got != listed[name] {
			problems = append(problems, fmt.Sprintf(
				"%s does not match %s:\n           recorded %s\n           actual   %s",
				name, manifestName, listed[name], got))
		}
	}

	// The converse of the loop above — see the package comment. An artifact
	// present in the directory but described by no row would ship inside the
	// release with no recorded identity at all.
	entries, rerr := os.ReadDir(dir)
	if rerr != nil {
		return nil, nil, fmt.Errorf("could not read %s: %w", dir, rerr)
	}
	var unlisted []string
	for _, e := range entries {
		name := e.Name()
		if name == manifestName {
			continue
		}
		if _, ok := listed[name]; !ok {
			unlisted = append(unlisted, name)
		}
	}
	if len(unlisted) > 0 {
		sort.Strings(unlisted)
		problems = append(problems, fmt.Sprintf(
			"%d file(s) in %s are described by no row in %s: %s",
			len(unlisted), dir, manifestName, strings.Join(unlisted, ", ")))
	}

	// Only on a clean result. The note ASSERTS something ("each re-read and
	// matching"), so printing it above a FAIL line would put a false claim in
	// the run's output — a smaller version of the defect this tool exists to
	// close. The problems below say what happened when there are any.
	if len(problems) == 0 {
		notes = append(notes, fmt.Sprintf(
			"        %s: %d entries, each re-read and matching, and nothing beside them unlisted",
			manifestName, len(order)))
	}
	return problems, notes, nil
}

// parseManifest reads the manifest strictly. Anything it cannot parse with
// certainty is an error rather than a skipped line: a row silently ignored is a
// file silently unverified, and this tool exists because that trade is the one
// this repository keeps having to undo.
func parseManifest(manifestPath string) (listed map[string]string, order []string, err error) {
	f, err := os.Open(manifestPath)
	if err != nil {
		return nil, nil, fmt.Errorf("could not read the manifest: %w", err)
	}
	defer f.Close()

	listed = map[string]string{}
	sc := bufio.NewScanner(f)
	for line := 1; sc.Scan(); line++ {
		text := sc.Text()
		if text == "" {
			return nil, nil, fmt.Errorf("%s:%d: blank line", manifestPath, line)
		}
		if strings.HasPrefix(text, `\`) {
			// coreutils prefixes a row with a backslash when the filename
			// contains a newline or a backslash, and escapes it in the name.
			// Release artifacts have plain names; rather than implement an
			// unescaper that would be exercised by nothing, refuse to guess.
			return nil, nil, fmt.Errorf("%s:%d: escaped filename (leading backslash) is not supported", manifestPath, line)
		}
		sum, name, ok := strings.Cut(text, fieldSeparator)
		if !ok {
			return nil, nil, fmt.Errorf("%s:%d: not %q-separated: %q", manifestPath, line, fieldSeparator, text)
		}
		if len(sum) != digestHexLen {
			return nil, nil, fmt.Errorf("%s:%d: digest is %d hex characters, want %d: %q", manifestPath, line, len(sum), digestHexLen, sum)
		}
		if _, derr := hex.DecodeString(sum); derr != nil {
			return nil, nil, fmt.Errorf("%s:%d: digest is not hexadecimal: %q", manifestPath, line, sum)
		}
		if err := checkName(name); err != nil {
			return nil, nil, fmt.Errorf("%s:%d: %w", manifestPath, line, err)
		}
		if _, dup := listed[name]; dup {
			return nil, nil, fmt.Errorf("%s:%d: %q is listed more than once", manifestPath, line, name)
		}
		listed[name] = strings.ToLower(sum)
		order = append(order, name)
	}
	if err := sc.Err(); err != nil {
		return nil, nil, fmt.Errorf("could not read %s: %w", manifestPath, err)
	}
	if len(order) == 0 {
		// An empty manifest verifies trivially and would report a green run over
		// nothing at all.
		return nil, nil, fmt.Errorf("%s lists no files", manifestPath)
	}
	return listed, order, nil
}

// checkName rejects anything that is not a plain basename. A row carrying a
// path separator would escape the manifest's own directory when verified, and
// the two dot names name a directory rather than an artifact.
func checkName(name string) error {
	switch name {
	case "", ".", "..":
		return fmt.Errorf("%q is not a filename", name)
	}
	if strings.ContainsAny(name, `/\`+"\n\r") {
		return fmt.Errorf("%q is not a plain basename", name)
	}
	return nil
}

// digest returns the lowercase hex SHA-256 of the file's contents, streamed so
// that artifact size is not a memory question.
func digest(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", fmt.Errorf("could not read %s: %w", path, err)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}
